In [1]:
import sys
sys.path.append("../")

In [2]:
from prophecy.get_data import WeatherEnergy

In [4]:
data = WeatherEnergy(limit =-1,
                    offset = 0,
                    refine = "Hauts-de-France",
                    target = "eolien",
                    city = ["Heudicourt", "Riencourt"],
                    years = 10)

In [5]:
lat_lan = data.get_city_lonlan()

In [7]:
lat_lan

{'Heudicourt': [50.02283, 3.07807], 'Riencourt': [49.9221127, 2.0503814]}

In [8]:
weather_data = data.get_weather()

In [15]:
weather_data.info()

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 87480 entries, 2013-03-14 00:00:00 to 2023-03-06 23:00:00
Data columns (total 33 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   temperature_2m                 87480 non-null  float64
 1   relativehumidity_2m            87480 non-null  float64
 2   dewpoint_2m                    87480 non-null  float64
 3   apparent_temperature           87480 non-null  float64
 4   pressure_msl                   87480 non-null  float64
 5   surface_pressure               87480 non-null  float64
 6   precipitation                  87480 non-null  float64
 7   rain                           87480 non-null  float64
 8   snowfall                       87480 non-null  float64
 9   cloudcover                     87480 non-null  float64
 10  cloudcover_low                 87480 non-null  float64
 11  cloudcover_mid                 87480 non-null  float64
 12  cloudcover_high                87480 non-null  float64
 13  shortwave_radiation            87480 non-null  float64
 14  direct_radiation               87480 non-null  float64
 15  direct_normal_irradiance       87480 non-null  float64
 16  diffuse_radiation              87480 non-null  float64
 17  windspeed_10m                  87480 non-null  float64
 18  windspeed_100m                 87480 non-null  float64
 19  winddirection_10m              87480 non-null  float64
 20  winddirection_100m             87480 non-null  float64
 21  windgusts_10m                  87480 non-null  float64
 22  et0_fao_evapotranspiration     87480 non-null  float64
 23  weathercode                    87480 non-null  float64
 24  vapor_pressure_deficit         87480 non-null  float64
 25  soil_temperature_0_to_7cm      87480 non-null  float64
 26  soil_temperature_7_to_28cm     87480 non-null  float64
 27  soil_temperature_28_to_100cm   87480 non-null  float64
 28  soil_temperature_100_to_255cm  87480 non-null  float64
 29  soil_moisture_0_to_7cm         87480 non-null  float64
 30  soil_moisture_7_to_28cm        87480 non-null  float64
 31  soil_moisture_28_to_100cm      87480 non-null  float64
 32  soil_moisture_100_to_255cm     87480 non-null  float64
dtypes: float64(33)
memory usage: 22.7 MB

In [18]:
energy_production = data.get_energy_production()

In [19]:
energy_production.head()

,code_insee_region,libelle_region,nature,date,heure,date_heure,consommation,thermique,nucleaire,eolien,...,tco_nucleaire,tch_nucleaire,tco_eolien,tch_eolien,tco_solaire,tch_solaire,tco_hydraulique,tch_hydraulique,tco_bioenergies,tch_bioenergies
time,,,,,,,,,,,,,,,,,,,,,
2013-01-01 00:00:00,32,Hauts-de-France,Données définitives,2013-01-01,00:00,2012-12-31T23:00:00+00:00,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,None,None,None,None
2013-01-01 00:30:00,32,Hauts-de-France,Données définitives,2013-01-01,00:30,2012-12-31T23:30:00+00:00,"5,989.0",828.0,"4,499.0","1,115.0",...,NaN,NaN,NaN,NaN,NaN,NaN,None,None,None,None
2013-01-01 01:00:00,32,Hauts-de-France,Données définitives,2013-01-01,01:00,2013-01-01T00:00:00+00:00,"5,832.0",830.0,"4,500.0","1,062.0",...,NaN,NaN,NaN,NaN,NaN,NaN,None,None,None,None
2013-01-01 01:30:00,32,Hauts-de-France,Données définitives,2013-01-01,01:30,2013-01-01T00:30:00+00:00,"5,926.0",833.0,"4,499.0","1,014.0",...,NaN,NaN,NaN,NaN,NaN,NaN,None,None,None,None
2013-01-01 02:00:00,32,Hauts-de-France,Données définitives,2013-01-01,02:00,2013-01-01T01:00:00+00:00,"5,695.0",828.0,"4,497.0",951.0,...,NaN,NaN,NaN,NaN,NaN,NaN,None,None,None,None

In [20]:
merged_df = data.merged()

In [26]:
merged_df.sort_values(by="time")

,temperature_2m,relativehumidity_2m,dewpoint_2m,apparent_temperature,pressure_msl,surface_pressure,precipitation,rain,snowfall,cloudcover,...,vapor_pressure_deficit,soil_temperature_0_to_7cm,soil_temperature_7_to_28cm,soil_temperature_28_to_100cm,soil_temperature_100_to_255cm,soil_moisture_0_to_7cm,soil_moisture_7_to_28cm,soil_moisture_28_to_100cm,soil_moisture_100_to_255cm,eolien
time,,,,,,,,,,,,,,,,,,,,,
2013-03-14 00:00:00,-4.5,94.0,-5.2,-3.0,"1,012.0","1,001.3",0.0,0.0,0.0,35.5,...,0.0,1.6,2.2,4.6,5.4,0.4,0.4,0.4,0.4,133.0
2013-03-14 01:00:00,-5.6,95.0,-6.3,-3.6,"1,012.5","1,001.9",0.0,0.0,0.0,31.5,...,0.0,1.6,2.2,4.6,5.4,0.4,0.4,0.4,0.4,139.0
2013-03-14 02:00:00,-6.2,95.5,-6.8,-3.5,"1,012.9","1,002.2",0.0,0.0,0.0,26.0,...,0.0,1.4,2.2,4.6,5.4,0.4,0.4,0.4,0.4,125.0
2013-03-14 03:00:00,-6.6,96.0,-7.0,-3.7,"1,012.9","1,002.2",0.0,0.0,0.0,18.5,...,0.0,1.3,2.2,4.5,5.4,0.4,0.4,0.4,0.4,122.0
2013-03-14 04:00:00,-6.9,96.0,-7.5,-3.9,"1,012.9","1,002.2",0.0,0.0,0.0,12.5,...,0.0,1.2,2.2,4.5,5.4,0.4,0.4,0.4,0.4,140.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2023-03-06 19:00:00,6.0,67.0,0.4,2.0,"1,005.9",995.5,0.0,0.0,0.0,100.0,...,0.3,5.7,5.2,5.3,7.5,0.3,0.3,0.4,0.4,"1,797.0"
2023-03-06 20:00:00,5.2,78.0,1.6,1.6,"1,005.8",995.4,0.0,0.0,0.0,98.0,...,0.2,5.2,5.2,5.3,7.5,0.3,0.3,0.4,0.4,"1,768.0"
2023-03-06 21:00:00,5.0,78.5,1.5,1.3,"1,005.5",995.2,0.0,0.0,0.0,99.0,...,0.2,4.9,5.1,5.4,7.5,0.3,0.3,0.4,0.4,"1,974.0"
2023-03-06 22:00:00,4.7,79.0,1.4,0.9,"1,005.0",994.7,0.1,0.1,0.0,100.0,...,0.2,4.7,5.1,5.4,7.5,0.3,0.3,0.4,0.4,"1,928.0"
2023-03-06 23:00:00,4.5,79.5,1.2,0.4,"1,004.7",994.3,0.1,0.1,0.0,100.0,...,0.2,4.5,5.1,5.4,7.5,0.3,0.3,0.4,0.4,"2,190.0"